name: Deploy WS

on:
    push:
        branches: [main]

jobs:
    build:
        name: Build the WS
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                file: ./docker/Dockerfile.ws
                push: true
                tags: efty112/test-turbo-app-ws:${{github.sha}}
                
    # Code FOR Deployment:
    # deploy:
    #     name: Deploy the WS to AWS
    #     runs-on: ubuntu-latest